### ISSUE TITLE
KeyError when trying to get vehicle status

### ISSUE THREAD

**Issue by daveoley** [bdr99/pymazda#1] opened 2021-03-04 02:52 UTC
The remote_info for my '21 Mazda CX-5 does not contain all the keys that are being accessed in get_vehicle_status().

The missing keys are:

- RemDrvDistDActlKm
- FLTPrsDispPsi
- FRTPrsDispPsi
- RLTPrsDispPsi
- RRTPrsDispPsi

The TPMS information for this car only has the following fields:

- RRTyrePressWarn
- MntTyreAtFlg
- RLTyrePressWarn
- TPMSStatus
- FRTyrePressWarn
- FLTyrePressWarn

Perhaps the TPMS and distance aren't available yet because the car hasn't been driven very long?

**Comment by bdr99** [comment] 2021-03-04 03:04
Thanks for the issue report, and also thanks for debugging the issue to find the root cause!

Would you mind sharing your entire result of calling `get_vehicle_status()`? (After removing any personal info, of course.)

**Comment by bdr99** [comment] 2021-03-04 03:06
Also, do you see the tire pressure and fuel distance values if you log into the MyMazda mobile app?

**Comment by daveoley** [comment] 2021-03-04 03:14
Here's the entire response:

```js
{'alertInfos': [{'TnsLight': {'LghtSwState': 0, 'LightCombiSWMode': 1, 'TnsLamp': 0}, 'HazardLamp': {'HazardSw': 0}, 'UsbPositionAccuracy': 100, 'Pw': {'PwPosRr': 0, 'PwPosDrv': 0, 'PwPosPsngr': 0, 'PwPosRl': 0}, 'PositionInfo': {'AcquisitionDatetime': '20210303002125', 'Latitude': XX.XXXXXX, 'LatitudeFlag': 0, 'Longitude': XX.XXXXXX, 'LongitudeFlag': 0}, 'OccurrenceDate': '20210303002248', 'PositionInfoCategory': 4, 'Door': {'SrTiltSignal': 0, 'FuelLidOpenStatus': 1, 'DrStatHood': 0, 'LockLinkSwRr': 0, 'DrStatRr': 0, 'LockLinkSwRl': 0, 'DrStatPsngr': 0, 'DrStatDrv': 0, 'SrSlideSignal': 0, 'AllDrSwSignal': 0, 'DrStatRl': 0, 'DrOpnWrn': 0, 'LockLinkSwDrv': 0, 'DrStatTrnkLg': 0, 'LockLinkSwPsngr': 0}, 'DcmPositionAccuracyEntity': {}}], 'remoteInfos': [{'ResidualFuel': {'FuelSegementDActl': 100.0}, 'RegularMntInformation': {'MntSetDistKm': 65535, 'MntSetDistMile': 40721}, 'DriveInformation': {'Drv1AvlFuelG': 12.2, 'Drv1AvlFuelE': 8.2, 'Drv1AmntFuel': 0.0, 'OdoDispValue': 119.1, 'Drv1Distnc': 1.248, 'OdoDispValueMile': 74.0, 'Drv1DrvTm': 199}, 'TPMSInformation': {'RRTyrePressWarn': 3, 'MntTyreAtFlg': 0, 'RLTyrePressWarn': 3, 'TPMSStatus': 3, 'FRTyrePressWarn': 3, 'FLTyrePressWarn': 3}, 'SeatBeltInformation': {'FirstRowBuckleDriver': 1, 'RLOCSStatDActl': 1, 'OCSStatus': 1, 'RROCSStatDActl': 1, 'SeatBeltWrnDRq': 0, 'RCOCSStatDActl': 1, 'SeatBeltStatDActl': '00', 'FirstRowBucklePsngr': 0}, 'ElectricalInformation': {'PowerControlStatus': 1, 'EngineState': 3}, 'BatteryStatus': {'SocEcmAEst': 127.5}, 'UsbPositionAccuracy': 58, 'MntSCRInformation': {'UreaTankLevel': 127.5, 'RemainingMileage': 65535, 'MntSCRAtFlg': 0}, 'OccurrenceDate': '20210302224902', 'PositionInfo': {'AcquisitionDatetime': '20210302224859', 'Latitude': 30.284479, 'LatitudeFlag': 0, 'LongitudeFlag': 0, 'Longitude': 97.684653}, 'PositionInfoCategory': 4, 'OilMntInformation': {'RemOilDistMile': 6600, 'DROilDeteriorateLevel': 90, 'MntOilAtFlg': 1, 'OilDtrInitTime': 12, 'OilDeteriorateWarning': 0, 'OilDtrInitDistMile': 6835, 'OilLevelWarning': 0, 'RemOilDistK': 11000, 'MntOilLvlAtFlg': 0, 'OilDtrInitDistKm': 11000, 'OilLevelSensWarnBRq': 0, 'OilLevelStatusMonitor': 10}, 'WguidStatus': {}, 'DcmPositionAccuracyEntity': {}}], 'resultCode': '200S00', 'visitNo': 'GW01210304031314455634'}
```

The Mazda app only shows the fuel percent and odometer on the Vehicle Status page. It shows a check mark next to the Tire Pressure in the Health Report.

**Comment by bdr99** [comment] 2021-03-04 03:20
OK, thanks for sharing that. Interesting, I'll have to add some logic to check if those values are present.

I've only tested this library on my 2021 Mazda3 so it's very possible that some of the values only exist on certain models.

**Comment by daveoley** [comment] 2021-03-04 03:24
No problem! 

It's very possible that those values will show up once I've driven the car more. It only has 70 miles on it, so the TPMS might not have measured values yet.

**Comment by bdr99** [comment] 2021-03-04 03:27
Yes that is also a possibility. Please let me know if those values show up for you later!

**Comment by bdr99** [comment] 2021-03-04 04:45
@daveoley I just published version 0.0.9 which adds some additional checks to handle missing values. The missing values should now resolve to `None` instead of raising an error. Can you try it and let me know if it works for you?

**Comment by daveoley** [comment] 2021-03-05 03:03
That fixed it for me, no more KeyError.

```js
{'lastUpdatedTimestamp': '20210302224902', 'latitude': XX.XXXXXX, 'longitude': -XX.XXXXXX, 'positionTimestamp': '20210302224859', 'fuelRemainingPercent': 100.0, 'fuelDistanceRemainingKm': None, 'odometerKm': 119.1, 'doors': {'driverDoorOpen': False, 'passengerDoorOpen': False, 'rearLeftDoorOpen': False, 'rearRightDoorOpen': False, 'trunkOpen': False, 'hoodOpen': False, 'fuelLidOpen': True}, 'doorLocks': {'driverDoorUnlocked': False, 'passengerDoorUnlocked': False, 'rearLeftDoorUnlocked': False, 'rearRightDoorUnlocked': False}, 'windows': {'driverWindowOpen': False, 'passengerWindowOpen': False, 'rearLeftWindowOpen': False, 'rearRightWindowOpen': False}, 'hazardLightsOn': False, 'tirePressure': {'frontLeftTirePressurePsi': None, 'frontRightTirePressurePsi': None, 'rearLeftTirePressurePsi': None, 'rearRightTirePressurePsi': None}}
```

**Comment by bdr99** [comment] 2021-03-07 19:30
Ok great! I'm going to close this issue then. Thanks again for your help.

**Closed by bdr99** 2021-03-07 19:30 UTC
